spring:
  datasource:
    url: "jdbc:h2:file:./src/main/resources/db/taskdb;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 3jj2ag9hpk2apiihddacenjuol
            client-secret: 1r8tokv532q74sgp1sj27sb7uvnifd6dcnei7ifr1udse96hiqr1
            scope:
              - email
              - openid
              - phone
            # Spring Security by default uses a redirect-uri in the format: {baseUrl}/login/oauth2/code/{registrationId}
            # For example: http://localhost:8080/login/oauth2/code/cognito
            # See more: https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-redirect-uri
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"

        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_AbjCAMvIs
            user-name-attribute: username

  application:
    name: tasksmanager
    cognito:
      logout-redirect-uri: http://localhost:8080

  jackson:
    mapper:
      accept-case-insensitive-enums: true


server:
  error:
    include-message: always
    include-stacktrace: always


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF        # Disable raw SQL logs unless needed
    com.yourcompany: DEBUG         # Your app's packages

  file:
    name: logs/app.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"


